/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-nocheck

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  mySidebar: {
    "Getting Started": [
      "getting-started/overview",
      //"getting-started/Catalyst",

      {
        type: "category",
        label: "Cardano Components",
        items: [
          "getting-started/cardano-components",
          "getting-started/installing-cardano-node",
          "getting-started/running-cardano",
          "getting-started/installing-cardano-wallet",
          "getting-started/wallet-cardano",
        ],
      },
      {
        type: "category",
        label: "Các công cụ",
        items: [
          "getting-started/blockfrost",
          "getting-started/cardanocli-js",
          "getting-started/cardano-wallet-js",
          "getting-started/dandelion-apis",
          "getting-started/ogmios",
          "getting-started/cardanosharp-wallet",
          {
            type: "category",
            label: "Mesh (Web3 SDK)",
            items: [
              {
                type: 'autogenerated',
                dirName: 'getting-started/mesh',
              },
            ],
          },
          {
            type: "category",
            label: "Blockforst (Web3 SDK)",
            items: [
              {
                type: 'autogenerated',
                dirName: 'getting-started/blockforst',
              },
            ],
          },
          //{
          //  type: "category",
          //  label: "Serialization-Lib",
          //  items: [
          //    "getting-started/cardano-serialization-lib/overview",
          //"getting-started/cardano-serialization-lib/prerequisite-knowledge",
          //"getting-started/cardano-serialization-lib/generating-keys",
          //"getting-started/cardano-serialization-lib/generating-transactions",
          //"getting-started/cardano-serialization-lib/transaction-metadata",
          // ],
          // },
        ],
      },
      "getting-started/technical-concepts",
      "getting-started/testnets-and-devnets",
      "getting-started/cardano-developer-community",
      "getting-started/videos",
    ],
    "Tạo Hợp đồng thông minh": [
      "smart-contracts/overview",
      "smart-contracts/smart-contracts-cardano",
      "smart-contracts/marlowe",
      "smart-contracts/plutus",
       "smart-contracts/aiken",   
      "smart-contracts/opshin",
      "smart-contracts/video_demo_smartcontract",
    ],
    "Khoa học Haskell": [
      "haskell_iog/README",
      "haskell_iog/intro_haskell",
      "haskell_iog/Intro_to_Haskell_and_tools",
      "haskell_iog/Functions-Data-Types-and-Signatures",
      "haskell_iog/Conditions-and-helper-constructions",
      "haskell_iog/Pattern-matching",
      "haskell_iog/Improving-and-combining-functions",
      "haskell_iog/Recursion-and-folds",
      "haskell_iog/Intro-to-Type-Classes",
      "haskell_iog/Creating-non-parameterized-types",
      "haskell_iog/Creating-parameterized-and-recursive-types",
      "haskell_iog/Creating-Type-Classes-and-Instances",
    ],
    "Khóa 2-Plutus của Dr.Lars": [
      "dr-lars-lession/overview",
      "dr-lars-lession/week1",
      "dr-lars-lession/week2",
      "dr-lars-lession/week3",
      "dr-lars-lession/week4",
      "dr-lars-lession/week5",
      "dr-lars-lession/week6",
      "dr-lars-lession/week7",
      "dr-lars-lession/week8",
      "dr-lars-lession/week9",
      "dr-lars-lession/week10",

    ],
    
    "Khóa 3-Plutus của Dr.Lars": [
      
      "dr-lars-lession/K_03/Lecture_01",
      "dr-lars-lession/K_03/Lecture_02",
      "dr-lars-lession/K_03/Lecture_03",
      "dr-lars-lession/K_03/Lecture_04",

    ],

    "Tích hợp với Cardano": [
      "integrate-cardano/overview",
      "integrate-cardano/creating-wallet-faucet",
      "integrate-cardano/multi-witness-transactions-cli",
      "integrate-cardano/multi_sign",
      "integrate-cardano/listening-for-payments-cli",
      "integrate-cardano/listening-for-payments-wallet",
      "integrate-cardano/dapps-connector",
      "integrate-cardano/Shop-pay-ada-Blockfrost",
      "integrate-cardano/testnet-faucet",
    ],
    "Khám phá Native Tokens": [
      "native-tokens/overview",
      "native-tokens/minting",
      //"native-tokens/mintingnfts",
      "native-tokens/Mint-nfts"
    // {
    //   type: "category",
    //    label: "Token Registry",
       // items: [{
          // Generate sidebar automatically from docs/native-tokens/token-registry
        //  type: 'autogenerated',
         // dirName: 'native-tokens/token-registry',
    //    },
	//	],
    //  },
    ],
    "Vận hành Stake Pool": [
      //"operate-a-stake-pool/note",
       {
         type: "category",
         label: "Stake Pool Course",
         items: [
           "stake-pool-course/overview",
           "stake-pool-course/introduction-to-cardano",
           "stake-pool-course/lesson-1",
           "stake-pool-course/lesson-2",
           "stake-pool-course/lesson-3",
           "stake-pool-course/lesson-4",
           "stake-pool-course/lesson-5",
           {
             type: "category",
             label: "Handbook",
             items: [
               "stake-pool-course/handbook/setup-virtual-box-written",
               "stake-pool-course/handbook/setup-a-server-on-aws-written",
               //"stake-pool-course/handbook/setup-firewall",
               "stake-pool-course/handbook/hardening-ubuntu",
               "stake-pool-course/handbook/install-cardano-node-written",
               "stake-pool-course/handbook/run-cardano-node-handbook",
               "stake-pool-course/handbook/use-cli",
               "stake-pool-course/handbook/utxo-model",
               "stake-pool-course/handbook/keys-addresses",
               "stake-pool-course/handbook/create-simple-transaction",
               "stake-pool-course/handbook/create-stake-pool-keys",
               "stake-pool-course/handbook/register-stake-keys",
               "stake-pool-course/handbook/generate-stake-pool-keys",
               "stake-pool-course/handbook/configure-topology-files",
               "stake-pool-course/handbook/register-stake-pool-metadata",
               "stake-pool-course/handbook/apply-logging-prometheus",
             ],
           },
           {
             type: "category",
             label: "Assignments",
             items: [
               "stake-pool-course/assignments/assignment-1",
               "stake-pool-course/assignments/assignment-2",
               "stake-pool-course/assignments/kes_period",
             ],
           },
         ],
       },
       {
         type: "category",
         label: "Operator Tools",
         items: [
           "operate-a-stake-pool/guild-ops-suite",
           "operate-a-stake-pool/ansible-cardano-node",
         ],
		 type: "category",
         label: "cntools",
         items: [
         "stake-pool-course/cntools/air-gap",
          "stake-pool-course/cntools/cntools-tao-pool-bao-mat",
          "stake-pool-course/cntools/cntools",
          "stake-pool-course/cntools/cntools-01",
          "stake-pool-course/cntools/cntools-02",
          "stake-pool-course/cntools/cntools-03",
          "stake-pool-course/cntools/cntools-04",
         ],
       },
       {
         type: "category",
         label: "Raspberry Pi Pool Kit",
         items: [
            "operate-a-stake-pool/Raspberry-Pi-pool-kit/raspberry-pi-os",
            "operate-a-stake-pool/Raspberry-Pi-pool-kit/Binary-Cardano-node-aarch64",
            "operate-a-stake-pool/Raspberry-Pi-pool-kit/note",
            
         ],
       },
       "operate-a-stake-pool/marketing-stake-pool",
	   "setup-application/dbSync",
       "setup-application/Staking",
       
    ],
    "Cài đặt và Ví dụ Plutus": [
      "setup-application/Installation",
      "setup-application/setup-node-mainnet",
      "setup-application/setup-node-testnet",
      "setup-application/recovery-phrase-wallet",
      "setup-application/step-by-step",
      "setup-application/Plutus_transactions_tutorial",
      "setup-application/Datums_redeemer_tutorial",
      "setup-application/Validator_scripts_tutorial",
    ],
    
    "Project Catalyst": [
      "project-catalyst/overview",
      "project-catalyst/funding-process",
      "project-catalyst/catalyst-funded",
      "project-catalyst/proposer",
      "project-catalyst/community-advisor",
	  "project-catalyst/yellow-and-red-card",
      "project-catalyst/voter",
      "project-catalyst/catalyst-registration-and-voting-guide",
      "project-catalyst/check-rewards",
      "project-catalyst/project-catalyst-community-resources",
	  
    ],
    
    "Cardano 4 UNI": [
      {
        type: "category",
        label: "Catalyst 4 students",
        items: [
	      "catalyst4students/overview",
	      "catalyst4students/daihocnguyentrai",
	      "catalyst4students/report",
        ],
      },
      "Cardano4uni/daihocgiaothongvantai",
      "Cardano4uni/web3-bootcamp-gtvt",
      "Cardano4uni/sv-dh-gtvt-gckh",
      "catalyst4students/daihocnguyentrai",
      "Cardano4uni/daihoccongnghiephn",
      "Cardano4uni/daihoc-kinhte-kythuat-congnghiep",
      
      

    ],
    "Các sự kiện": [
      "events/overview",
      "events/iohk-blog",
      "events/hotro-spo",
      "events/Cardano-coffee-lounge",
      "events/even-HN",
      "events/even-HCM",
      "events/even",
      "Cardano-summit-2022/Cardano-summit-2022-hanoi"
	    
    ],
    "SNET-360": [
        "sNET-360/deep-funding-round-2",
              
     ],
          
    // "Mang Project Catalyst Townhall đến Việt Nam": [
    //   "vn-townhall-channel/note",
    // ],
    // "Contribute to the Developer Portal": [
    //   "portal-contributors",
    //   "portal-contribute",
    //   "portal-style-guide",
    // ],
  },
};

module.exports = sidebars;
